PConfig:
  config_fpath: _configs_models/
  model: Grape_Phenology_TensorBatch
  model_parameters: grape_phenology:1
  latitude: 46
  longitude: -120
  start_date: '2023-01-01'
  output_vars:
  - PHENOLOGY
  input_vars:
  - DAY
  - TEMP
  - TMIN
  - TMAX
  - RAIN
  - IRRAD
  - DAYL
  - MIN_RH
  - AVG_RH
  - MAX_RH
  - MIN_DEWPT
  - AVG_DEWPT
  - MAX_DEWPT
  - WS_MPH
  - MAX_WS_MPH
  - ETO
DConfig:
  type: Param
  hidden_dim: 1024
  arch: EmbedFCGRU
  learning_rate: 0.0002
  lr_factor: 0.95
  batch_size: 12
  epochs: 400
DataConfig: 
  cultivar: All
  data_fpath: _data/processed_data/
  dtype: grape_phenology_
params:
- TBASEM
- TEFFMX
- TSUMEM
- TSUM1
- TSUM2
- TSUM3
- TSUM4
params_range:
- - 0
  - 15
- - 15
  - 45
- - 10
  - 100
- - 100
  - 1000
- - 100
  - 1000
- - 100
  - 1000
- - 100
  - 1000
log_path: /_runs/PaperExperiments/Phenology/ParamMTL/
run_name: param_zscore
seed: 2
